project:
  type: website
  output-dir: docs

website:
  title: "one carat blog"
  image: github_read.png
  favicon: favicon.png
  page-navigation: true
  page-footer: "Â© 2022, Jewel Johnson"
  opengraph: true
  site-url: "https://jeweljohnsonj.github.io/one-carat-blog/"
  repo-url: "https://github.com/jeweljohnsonj/one-carat-blog"
  repo-actions: [edit, issue]
  twitter-card: true
  google-analytics: G-EVCS615JQR
    
  navbar:
    logo: favicon.png
    right:
      - text: "Blog"
        href: blog.qmd
      - text: "Tutorials"
        href: tutorials.qmd
      - text: "About me"
        href: https://jeweljohnsonj.github.io/jewel_resume/
      - icon: github
        href: https://github.com/jeweljohnsonj/one-carat-blog
      - icon: twitter
        href: https://twitter.com/jeweljohnsonj
 
format:
  html:
    theme: slate
    css: styles.css
    toc: true
    toc-location: right
    toc-depth: 3
    toc-title: On this page
    html-math-method: katex
    number-sections: true
    smooth-scroll: true
    highlight-style: github
    code-link: true
    df-print: paged

citation: true

comments:
  giscus:
    repo: jeweljohnsonj/one-carat-blog 

editor: source

freeze: auto

# Extension settings
filters:
   - lightbox